# Generated by Django 5.0.3 on 2026-03-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_dialog_privatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_helpful',
            field=models.BooleanField(default=False, verbose_name='Полезный ответ'),
        ),
    ]
